#!/bin/bash
IS_LOWER()
{
var=$1
  return ${var,,}

}

#****************************
IS_ROOT()
{
if [ "$(id -u)" -ne "0" ]
then 
    return 1
else
   return 0
fi
}
#*****************************
IS_USER()
{
v=`id -u $1`
if [ $? -eq 0 ]
then
return 0
else
return 1
fi
}
IS_USER uzair
